// Event Type
export const EVENT = {
    BUTTON_CLICKED: 'BUTTON_CLICKED',
    PULL_DOWN_TO_REFRESH: 'PULL_DOWN_TO_REFRESH',
    SIGN_IN_COMPLETE: 'SIGN_IN_COMPLETE',
};

export const CSI = {
  FONTS_LOADED: 'FONTS_LOADED',
};

export const SCREEN = {
    AUTH_PAGE: 'AUTH_PAGE',
    BOOK_DETAILS_PAGE: 'BOOK_DETAILS_PAGE',
    PLAYER_PAGE: 'PLAYER_PAGE',
    HOME_PAGE: 'HOME_PAGE',
    SETTINGS_PAGE: 'SETTINGS_PAGE',
    SPLASH_PAGE: 'SPLASH_PAGE'
};

// Button types
export const BUTTON = {
    SIGN_IN_WITH_GOOGLE: 'SIGN_IN_WITH_GOOGLE',
    SIGN_OUT: 'SIGN_OUT'
};

// Sign In Providers
export const SIGN_IN_PROVIDERS = {
    GOOGLE: 'GOOGLE',
    FACEBOOK: 'FACEBOOK'
};