// Event Type
export const EVENT = {
    BUTTON_CLICKED: 'BUTTON_CLICKED',
    PULL_DOWN_TO_REFRESH: 'PULL_DOWN_TO_REFRESH',
    SIGN_IN_COMPLETE: 'SIGN_IN_COMPLETE',
    SEEK_SLIDER: 'SEEK_SLIDER'
};

// Button types
export const BUTTON = {
    SIGN_IN_WITH_GOOGLE: 'SIGN_IN_WITH_GOOGLE',
    SIGN_OUT: 'SIGN_OUT',
    SEEK_FORWARD: 'SEEK_FORWARD',
    SEEK_BACKWARD: 'SEEK_BACKWARD',
    PLAY: 'PLAY',
    PAUSE: 'PAUSE'
};

// Sign In Providers
export const SIGN_IN_PROVIDERS = {
    GOOGLE: 'GOOGLE',
    FACEBOOK: 'FACEBOOK'
};

export const CSI = {
    FONTS_LOADED: 'FONTS_LOADED',
    AUDIO_LOADED: 'AUDIO_LOADED',
    PLAYER_SETUP: 'PLAYER_SETUP'
};

export const SCREEN = {
    AUTH_PAGE: 'AUTH_PAGE',
    BOOK_DETAILS_PAGE: 'BOOK_DETAILS_PAGE',
    PLAYER_PAGE: 'PLAYER_PAGE',
    HOME_PAGE: 'HOME_PAGE',
    SETTINGS_PAGE: 'SETTINGS_PAGE',
    SPLASH_PAGE: 'SPLASH_PAGE'
};