# Generated by Django 2.2.6 on 2019-10-26 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gutenberg_id', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=1024, null=True)),
                ('isbn', models.CharField(max_length=13, null=True)),
                ('published_year', models.CharField(max_length=4, null=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_title', models.CharField(max_length=1024, null=True)),
                ('url', models.URLField(null=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Book')),
            ],
            options={
                'db_table': 'chapter',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256, null=True)),
                ('last_name', models.CharField(max_length=256, null=True)),
                ('description', models.TextField(null=True)),
                ('wikipedia_url', models.URLField(null=True)),
                ('books', models.ManyToManyField(to='backend.Book')),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='AudioRecording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length_seconds', models.IntegerField(null=True)),
                ('url', models.URLField(null=True)),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Chapter')),
            ],
            options={
                'db_table': 'audio_recording',
            },
        ),
    ]
