# Generated by Django 2.2.6 on 2019-11-10 04:49

import grequests
import requests
import xml
import xmltodict
import backend.scripts.utils as utils
from django.db import migrations


def populate_recordings(apps, schema_editor):
    pass  # This migration was moved to a script



class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20191110_0742'),
    ]

    operations = [
        migrations.RunPython(populate_recordings)
    ]
