# Generated by Django 2.2.6 on 2019-11-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', 'load_librivox_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librivoxbook',
            name='url_rss',
            field=models.URLField(max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='librivoxbook',
            name='url_text_source',
            field=models.URLField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='librivoxbook',
            name='url_zip_file',
            field=models.URLField(max_length=4096, null=True),
        ),
    ]
