# Generated by Django 2.2.6 on 2019-11-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20191110_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librivoxrecordings',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='librivoxrecordings',
            name='url',
            field=models.URLField(max_length=4096, null=True),
        ),
    ]
