# Generated by Django 2.2.6 on 2019-11-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_auto_20191110_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='librivox_books',
            field=models.ManyToManyField(to='backend.LibriVoxBook'),
        ),
    ]
