# Generated by Django 2.2.6 on 2019-11-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_author_librivox_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='librivox_books',
            field=models.ManyToManyField(null=True, to='backend.LibriVoxBook'),
        ),
    ]
