# Generated by Django 2.2.6 on 2019-11-10 21:28

from django.db import migrations


def clean_author_names(apps, schema_editor):
    Author = apps.get_model('backend', 'Author')

    for a in Author.objects.all():
        a.first_name = a.first_name.lstrip().rstrip()
        a.last_name = a.last_name.lstrip().rstrip()
        a.save()


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20191110_2055'),
    ]

    operations = [
        migrations.RunPython(clean_author_names)
    ]
