# Generated by Django 2.2.6 on 2019-10-26 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20191026_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='book_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Book'),
        ),
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterModelTable(
            name='subject',
            table='subject',
        ),
    ]
