# Generated by Django 2.2.6 on 2019-10-26 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20191026_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatURI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_url', models.URLField(null=True)),
                ('book_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Book')),
            ],
            options={
                'db_table': 'format_uris',
            },
        ),
    ]
