# Generated by Django 2.2.6 on 2019-11-10 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20191110_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='book',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='books',
            new_name='gutenberg_books',
        ),
        migrations.DeleteModel(
            name='AudioRecording',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
