# Generated by Django 2.2.6 on 2019-11-10 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20191110_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodreadsbook',
            old_name='book',
            new_name='gutenberg_book',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='books',
            new_name='gutenberg_books',
        ),
    ]
