# Generated by Django 2.2.6 on 2019-10-26 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_formaturi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formaturi',
            old_name='format_url',
            new_name='url',
        ),
    ]
