# Generated by Django 2.2.6 on 2019-10-26 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20191026_2003'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='formaturi',
            table='format_uri',
        ),
    ]
