# Generated by Django 2.2.6 on 2019-11-10 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20191110_2248'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='GutenbergBook',
        ),
    ]
