# Generated by Django 2.2.6 on 2019-10-26 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20191026_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formaturi',
            old_name='book_id',
            new_name='book',
        ),
    ]
