# Generated by Django 2.2.6 on 2019-11-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20191110_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='description',
        ),
        migrations.RemoveField(
            model_name='gutenbergbook',
            name='album_art_url',
        ),
        migrations.RemoveField(
            model_name='gutenbergbook',
            name='description',
        ),
        migrations.AddField(
            model_name='goodreadsbook',
            name='gutenberg_id',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='librivoxrecordings',
            name='librivox_id',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterModelTable(
            name='gutenbergbook',
            table='gutenberg_book',
        ),
    ]
