# Generated by Django 2.2.6 on 2019-10-26 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20191026_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='book_id',
            new_name='book',
        ),
    ]
