# Generated by Django 2.2.6 on 2019-11-10 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20191110_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, null=True)),
                ('text_url', models.URLField(max_length=4096, null=True)),
                ('audio_url', models.URLField(max_length=4096, null=True)),
                ('gutenberg_book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.GutenbergBook', unique=True)),
                ('librivox_book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.LibriVoxBook', unique=True)),
            ],
            options={
                'db_table': 'audiobook',
            },
        ),
        migrations.CreateModel(
            name='AudiobookChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('duration', models.CharField(max_length=32, null=True)),
                ('url', models.URLField(max_length=4096, null=True)),
                ('audiobook', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Audiobook', unique=True)),
            ],
            options={
                'db_table': 'audiobook_chapter',
            },
        ),
        migrations.AddField(
            model_name='author',
            name='audio_books',
            field=models.ManyToManyField(to='backend.Audiobook'),
        ),
    ]
