# Generated by Django 2.2.6 on 2019-11-10 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20191110_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='gutenberg_book',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.GutenbergBook'),
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='librivox_book',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.LibriVoxBook'),
        ),
    ]
