# Generated by Django 2.2.6 on 2019-11-10 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20191110_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobookchapter',
            name='audiobook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Audiobook'),
        ),
    ]
