# Generated by Django 2.2.6 on 2019-10-26 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20191026_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapter_num',
            field=models.IntegerField(null=True),
        ),
    ]
