# Generated by Django 2.2.6 on 2019-11-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20191110_2347'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LibriVoxRecordings',
            new_name='LibriVoxRecording',
        ),
        migrations.AddField(
            model_name='audiobook',
            name='ratings_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
