# Generated by Django 2.2.6 on 2019-11-10 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20191110_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiobook',
            old_name='ratings_count',
            new_name='goodreads_ratings_count',
        ),
    ]
