# Generated by Django 2.2.6 on 2019-10-27 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_chapter_chapter_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='chapter_num',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='chapter_title',
            new_name='title',
        ),
    ]
