# Generated by Django 2.2.6 on 2019-11-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20191110_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiobookchapter',
            old_name='url',
            new_name='audio_url',
        ),
        migrations.AddField(
            model_name='audiobook',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='primary_image_url',
            field=models.URLField(max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='secondary_image_url',
            field=models.URLField(max_length=4096, null=True),
        ),
    ]
