# Generated by Django 2.2.6 on 2019-11-11 00:16

from django.db import migrations
from django.utils.html import strip_tags


def create_audiobooks(apps, schema_editor):
    LibriVoxBook = apps.get_model('backend', 'LibriVoxBook')
    GutenbergBook = apps.get_model('backend', 'GutenbergBook')
    GoodreadsBook = apps.get_model('backend', 'GoodreadsBook')
    Audiobook = apps.get_model('backend', 'Audiobook')

    for librivox_book in LibriVoxBook.objects.all():
        gutenberg_book = GutenbergBook.objects.filter(gutenberg_id=librivox_book.gutenberg_id).first()

        if gutenberg_book is not None:
            goodreads_book = GoodreadsBook.objects.filter(gutenberg_book_id=gutenberg_book.id).first()
        else:
            goodreads_book = None

        # Set title and description
        audiobook = Audiobook()
        audiobook.title = librivox_book.title
        audiobook.description = strip_tags(librivox_book.description)

        audiobook.gutenberg_book = gutenberg_book
        audiobook.librivox_book = librivox_book

        # Set Audio and Text URLs
        if gutenberg_book is not None:
            audiobook.text_url = gutenberg_book.get_text_url()
        else:
            audiobook.text_url = librivox_book.get_text_url()

        audiobook.audio_url = librivox_book.get_audio_url()


        # Set Goodreads ratings count if there's a match between rating and author
        if goodreads_book is not None:
            # Check if authors match and set ratings count from Goodreads
            for author in librivox_book.author_set.union(gutenberg_book.author_set):
                if goodreads_book.is_authored_by(author):
                    audiobook.goodreads_ratings_count = goodreads_book.ratings_count


        print(librivox_book)
        print(gutenberg_book)
        print(goodreads_book)
        print(audiobook)

        audiobook.save()


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20191111_0036'),
    ]

    operations = [
        migrations.RunPython(create_audiobooks)
    ]
