# Generated by Django 2.2.6 on 2019-11-11 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20191111_0202'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='audiobook',
            unique_together={('gutenberg_book', 'librivox_book')},
        ),
    ]
