# Generated by Django 2.2.6 on 2019-11-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_goodreadsbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='gutenberg_id',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
