# Generated by Django 2.2.6 on 2019-11-11 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20191111_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='gutenberg_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.GutenbergBook'),
        ),
    ]
