# Generated by Django 2.2.6 on 2019-11-11 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20191111_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='goodreads_ratings_count',
            field=models.IntegerField(null=True),
        ),
    ]
