# Generated by Django 2.2.6 on 2019-11-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20191105_0511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='book',
        ),
        migrations.AddField(
            model_name='subject',
            name='book',
            field=models.ManyToManyField(to='backend.Book'),
        ),
    ]
