# Generated by Django 2.2.6 on 2019-11-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20191111_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='has_audio',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='language',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
