# Generated by Django 2.2.6 on 2019-11-11 06:18

from django.db import migrations
from backend.models import *


def set_additional_fields(apps, schema_editor):
    for i, a in enumerate(Audiobook.objects.all()):
        print(i)

        librivox_book = a.librivox_book
        a.has_audio = a.audiobookchapter_set.count() > 0
        a.language = librivox_book.language
        a.save()

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20191111_0622'),
    ]

    operations = [
        migrations.RunPython(set_additional_fields)
    ]
