# Generated by Django 2.2.6 on 2019-11-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20191105_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(null=True, unique=True),
        ),
    ]
