# Generated by Django 2.2.6 on 2019-11-07 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20191105_0521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodreadsbook',
            name='gutenberg_id',
        ),
        migrations.AddField(
            model_name='goodreadsbook',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='gutenberg_id',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('first_name', 'last_name')},
        ),
        migrations.RemoveField(
            model_name='author',
            name='wikipedia_url',
        ),
    ]
