# Generated by Django 2.2.6 on 2019-11-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20191111_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='isbn',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='isbn13',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
