# Generated by Django 2.2.6 on 2019-11-11 08:43
from django.db import migrations
from backend.models import *


def fill_isbn(apps, schema_editor):
    for i, a in enumerate(Audiobook.objects.all()):
        print(i)

        gutenberg_book = a.gutenberg_book
        if gutenberg_book is not None:
            goodreads_book = GoodreadsBook.objects.filter(gutenberg_book_id=gutenberg_book.id).first()
        else:
            goodreads_book = None

        if goodreads_book is not None:
            a.isbn = goodreads_book.isbn
            a.isbn13 = goodreads_book.isbn13
            a.save()


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20191111_0711'),
    ]

    operations = [
        migrations.RunPython(fill_isbn)
    ]
