# Generated by Django 2.2.6 on 2019-11-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20191107_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodreadsbook',
            name='goodreads_id',
            field=models.CharField(default=-1, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goodreadsbook',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='goodreadsbook',
            table='goodreads_book',
        ),
    ]
