# Generated by Django 2.2.6 on 2019-11-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20191107_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodreadsbook',
            name='isbn',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='goodreadsbook',
            name='isbn13',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
