# Generated by Django 2.2.6 on 2019-11-16 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20191111_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudiobookChapterGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, null=True)),
                ('audiobook', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Audiobook')),
            ],
            options={
                'db_table': 'audiobook_chapter_group',
            },
        ),
        migrations.AddField(
            model_name='audiobookchapter',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.AudiobookChapterGroup'),
        ),
    ]
