# Generated by Django 2.2.6 on 2019-11-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_auto_20191107_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiorecording',
            name='url',
            field=models.URLField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='url',
            field=models.URLField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='formaturi',
            name='url',
            field=models.URLField(max_length=1024, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='goodreadsbook',
            name='image_url',
            field=models.URLField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='goodreadsbook',
            name='link',
            field=models.URLField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='goodreadsbook',
            name='small_image_url',
            field=models.URLField(max_length=1024, null=True),
        ),
    ]
