# Generated by Django 2.2.6 on 2019-11-17 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_auto_20191116_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
