# Generated by Django 2.2.6 on 2019-11-08 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_auto_20191108_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodreadsbook',
            name='book',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Book'),
        ),
    ]
