# Generated by Django 2.2.6 on 2019-11-09 08:23

from django.db import migrations


def clean_isbn(apps, schema_editor):
    GoodreadsBook = apps.get_model('GoodreadsBook', 'Post')
    for book in GoodreadsBook.objects.all():
        if '.0' in book.isbn or '.0' in book.isbn13:
            book.isbn = book.isbn.replace('.0', '')
            book.isbn13 = book.isbn13.replace('.0', '')
            book.save()


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_auto_20191108_0541'),
    ]

    operations = [
        migrations.RunPython(clean_isbn)
    ]
