# Generated by Django 2.2.6 on 2019-11-17 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_auto_20191117_0332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiobookchapter',
            name='audiobook',
        ),
    ]
