# Generated by Django 2.2.6 on 2019-11-17 05:06

from django.db import migrations


def set_chapter_names(apps, schema_editor):
    Audiobook = apps.get_model('backend', 'Audiobook')

    for i, a in enumerate(Audiobook.objects.all()):
        print(i)
        chapter_groups = a.audiobookchaptergroup_set.all()
        if len(chapter_groups) == 1:
            c = chapter_groups.first()
            c.title = 'Chapters'
            c.save()

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_remove_audiobookchapter_audiobook'),
    ]

    operations = [
        migrations.RunPython(set_chapter_names)
    ]
