# Generated by Django 2.2.6 on 2019-11-10 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20191109_2049'),
    ]

    operations = [
        # Empty migration, need to create the LibriVox class first
    ]
