# Generated by Django 2.2.6 on 2019-11-10 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_auto_20191110_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibriVoxBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('librivox_id', models.CharField(max_length=32, null=True, unique=True)),
                ('title', models.CharField(max_length=1024, null=True)),
                ('description', models.TextField()),
                ('url_text_source', models.URLField(max_length=1024)),
                ('language', models.CharField(max_length=32, null=True)),
                ('copyright_year', models.CharField(max_length=4, null=True)),
                ('num_sections', models.IntegerField(null=True)),
                ('url_zip_file', models.URLField(max_length=1024, null=True)),
                ('totaltime', models.CharField(max_length=32, null=True)),
                ('totaltimesecs', models.IntegerField()),
            ],
            options={
                'db_table': 'librivox_book',
            },
        ),
        migrations.CreateModel(
            name='LibriVoxRecordings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, null=True)),
                ('duration', models.CharField(max_length=32, null=True)),
                ('url', models.URLField(max_length=1024, null=True)),
                ('librivox_book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.LibriVoxBook')),
            ],
            options={
                'db_table': 'librivox_recording',
            },
        ),
    ]
