export const SIGN_IN_WITH_GOOGLE_CLICKED = 'SIGN_IN_WITH_GOOGLE_CLICKED';
export const SIGN_IN_WITH_GOOGLE_SUCCESS = 'SIGN_IN_WITH_GOOGLE_SUCCESS';
export const SIGN_IN_WITH_GOOGLE_FAILED = 'SIGN_IN_WITH_GOOGLE_FAILED';
export const SIGN_IN_WITH_GOOGLE_ABANDONED = 'SIGN_IN_WITH_GOOGLE_ABANDONED';

// Settings buttons
export const SIGN_OUT_CLICKED = 'SIGN_OUT_CLICKED';

export const PULL_DOWN_TO_REFRESH = 'PULL_DOWN_TO_REFRESH';